api:
  build: .
  volumes:
    - .:/myapp
  ports:
    - "80:3000"
  container_name: api
db:
  image: postgres:9.4
  ports:
    - "5432:5432"
  container_name: db
  environment:
    - POSTGRES_PASSWORD=root
