# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: c9bc686486b83c3279ee19105892112f64e243fe22e0675c0f58c38d8748172a12f044777ea7f072cbba61cbc0f87d9af91bbe6588bc37d67149a1a47d954e56

test:
  secret_key_base: e2fe5118b4c297bbb87aeb15e207f9cc33a0b534cc9b0b0aff86f2401dff18133a40748182b9c0c1322b6c65c12ff7fb78bc444a901b2a698750edd44d19face

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
